---
# tasks file for setup-apache-role
- name: installing 'httpd'
  yum:
      name: httpd
      state: installed
  notify: start service



- name: copying file
  copy:
       src: /home/shiv/index.html
       dest: /tmp/index.html   
